// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRrgwSpf5FfpYUeuvUCZvLM73sr9XKaw',
    appId: '1:615247267950:web:306e9d273d43666afabe7f',
    messagingSenderId: '615247267950',
    projectId: 'budget-app-9e5cc',
    authDomain: 'budget-app-9e5cc.firebaseapp.com',
    storageBucket: 'budget-app-9e5cc.appspot.com',
    measurementId: 'G-XW8ZLBF3Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCtPI45FB4OJ8oCvIfo-65nP8d0SoqvE',
    appId: '1:615247267950:android:db703ddcd34003f2fabe7f',
    messagingSenderId: '615247267950',
    projectId: 'budget-app-9e5cc',
    storageBucket: 'budget-app-9e5cc.appspot.com',
  );
}
